
version: 1.0.{build}


build_script:
- cmd: >-


    REM pick a stack.yaml file

    copy etc\hs-deps\stack-8.2.yaml stack.yaml


    REM download stack

    curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386

    7z x stack.zip stack.exe


    REM install GHC

    stack setup --no-terminal | FIND /V "Extracting  "


    REM this is make preinstall, translated to CMD

    bash etc\build\version.sh

    stack runhaskell etc\build\gen_Operator.hs

    stack runhaskell etc\build\gen_Expression.hs


    REM compile conjure

    stack build --no-terminal --test --no-run-tests --ghc-options "-with-rtsopts=-M2G"


test_script:
- cmd: >-

    stack test --no-terminal --skip-ghc-check --ghc-options "-with-rtsopts=-M2G" --test-arguments "--hide-successes -p parse_print +RTS -s"


# shorter paths to avoid problems
clone_folder: "c:\\conjure"
environment:
  global:
    STACK_ROOT: "c:\\sr"

